fix(client/plyState): plyState variable not global
Error: Attempt to index a nil value (global 'plyState')
Reason: plyState was local only on main.lua
Fix: change plyState from local to global so it can be accessed from radio.lua and phone.lua