fix(client/proximity): cacheData
Error: attempt to index a nil value (global 'cachedData')
Reason: cachedData is null
Fix: Change cachedData to voiceModeData